# 应用
app:
  name: gin
  mode: debug # debug|test|release debug=本地环境 test=测试环境 release=生产环境
  port: 8080
  timezone: Asia/Shanghai
  proxies: 127.0.0.1/8080 # 代理地址多个地址用逗号分隔
  env: dev # dev|testing|production dev=本地环境 testing=测试环境 production=生产环境

# 数据库
databases:
  db-connection: mysql # 默认数据库
  # 慢查询的时间(ms) 超过这个时间会记录到日志中
  slow-query-duration: 3000ms # 3秒(time.Duration)

# Mysql数据库
mysql:
  driver: mysql
  # host: "username:password@tcp(127.0.0.1:3306)/databaseName?charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai"
  host: 127.0.0.1
  port: 3306
  username: root
  password: root
  database: gin
  # 慢查询的时间(ms) 超过这个时间会记录到日志中
  slow-query-duration: 3000ms # 3秒(time.Duration)

# Postgresql数据库
pgsql:
  driver: pgsql
  host: 127.0.0.1
  port: 5432
  username: testuser
  password: 123456
  database: testdb
  # 慢查询的时间(ms) 超过这个时间会记录到日志中
  slow-query-duration: 3000ms # 3秒(time.Duration)

# sqlite数据库
sqlite:
  driver: sqlite
  path: storage/data/gin.db
  # 慢查询的时间(ms) 超过这个时间会记录到日志中
  slow-query-duration: 3000ms # 3秒(time.Duration)

# sqlsrv数据库
sqlsrv:
  driver: sqlsrv
  host: 127.0.0.1
  port: 1433
  username: root
  password: root
  database: gin
  # 慢查询的时间(ms) 超过这个时间会记录到日志中
  slow-query-duration: 3000ms # 3秒(time.Duration)

# 缓存
cache:
  driver: "memory"  # memory|disk|redis # 为空默认内存缓存
  # Redis数据库
  redis:
    host: 127.0.0.1
    port: 6379
    db: 0
  # 内存缓存
  memory:
    default-expire: 5m # 默认过期时间(time.Duration)
    cleanup-interval: 10m # 清理数据的间隔时间(time.Duration)
  # 磁盘缓存
  disk:
    path: "storage/cache" # 缓存文件存放路径

# 跨域
cors:
  enabled: true # 是否开启跨域
  allow-origin: "*" # 允许访问的域名列表
  allow-headers: "*" # 允许的请求头列表
  expose-headers: "*" # 允许返回的响应头列表
  allow-methods: GET, POST, PUT, DELETE, OPTIONS # 允许的请求方法列表
  allow-credentials: "true" # 是否允许发送cookie

# Jwt
jwt:
  key: 123456789!@# # 加解密秘钥key
  exp: 7200 # 过期时间(单位秒) 2*60*60
  refresh-exp: 172800  # 刷新过期时间(单位秒) 2*24*60*60

# 日志配置
log:
  access: true # 是否记录访问日志
  max-size: 10 # 单个日志文件大小（MB）
  max-backups: 3  # 最多保留的旧日志文件数
  max-day: 28 # 保留的最大天数
  level: debug # 日志级别 debug|info|warn|error|fatal

# 翻译配置
i18n:
  dir: "storage/locales" # 翻译文件存放路径
  lang: "zh,en" # 默认语言,多个语言用逗号分隔

kafka:
  enabled: false # 是否启用kafka
  brokers:
    - "172.17.139.67:9092"

rabbitmq:
  enabled: false # 是否启用rabbitmq
  url: "amqp://admin:admin@172.30.117.79:5672/"